### ISSUE TITLE
Markdown code blocks not being rendered as <pre>s

### ISSUE THREAD

**Issue by LisaFC** [jekyll/jekyll#3724]
I've been experimenting with Markdown files as page sources in a Jekyll site, and it seems to work fine apart from code blocks - if the file has

```
My code example
```
..it's appearing in the site page as <p><code>My code example</code></p> (ie with code tags), rather than the expected <pre>My code example</pre> (with pre tags, which is how it's rendered in the Github UI). It means that, for example, all line breaks in code snippets are lost (making them in some cases unreadable), and any nice code box pre formatting in the CSS isn't used.

Obviously I can get around it by just replacing the backticks with pre tags but it would be nice to be able to copy in existing pure Markdown files without having to add inline HTML.

**Comment by pathawks** [comment]
This sounds like a quirk of your Markdown processor rather than a Jekyll issue.

**Comment by kleinfreund** [comment]
If you do something like this …

```markdown
… regular paragraph.

´´´html
<p>
    Paragraph code example<br>
    that needs multiple lines
</p>
´´´

New regular paragraph …
```

… make sure to always add two newlines between code blocks and paragraphs. Same goes for headings. Also notice that I used `´´´` as a replacement for the backticks so it looks like a perfectly fine code example.

Now if you already do that it would help to know which Markdown processor you're currently using. The default for Jekyll (i.e. you didn't set one yourself in the _config.yml) is kramdown.

**Comment by envygeeks** [comment]
Unfortunately there is nothing we can do about that as to apply your "hack" would possibly break other people's source.  You'll need to file a bug with whatever markdown processor you use or you can double check your source, quite often a misclosed ``` can lead to something like what happened to you as well as what @kleinfreund said (this is a known quirk with a few markdown processors.)

This is a not a problem in Jekyll, this is an upstream problem dependency problem. Sorry.

**Comment by envygeeks** [comment]
I am reopening this because it is actually Jekyll's problem, we default to Kramdown (https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml#L14) but Kramdown goes against everything Github teaches you about fenced codeblocks.

We should normalize fenced codeblocks so that they work the way Github teaches people instead of letting them figure out the hardway that `~~~` is Kramdown... not ```.  I don't actually know if Kramdown even has an option to support ``` but I know in my own library we normalize and I remembered that when I was thinking about this a second ago: https://github.com/envygeeks/ruby-content-pipeline/blob/master/lib/content/pipeline/filters/markdown.rb#L97

**Comment by LisaFC** [comment]
Thanks for that - I didn't realize that a)Jekyll defaulted to Kramdown or that b)Kramdown had such unfamiliar (to me as a Github user) syntax. Would be great if that was fixed, especially as a lot of the source text I'm using was originally used as Github READMEs and hence uses Github-flavoured Markdown. In the meantime will switch to another processor, which should hopefully solve my problem.

**Comment by diezcami** [comment]
I'd like to suggest using `redcarpet` as a preprocessor, along with a few extensions.
```
#_config.yml
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
```
I had the least problems with it compared to kramdown and rdiscount, but ymmv - just my 2 cents.

**Comment by envygeeks** [comment]
@diezcami That was the conclusion (from what I assumed) but I still think we need to normalize ~~~ to ``` just so people don't get confused, I've discussed it with @parkr but I've not convinced him of the benefits yet even though there are tons (in that we don't get tickets and help discussions) and that people don't get unexpected results.

**Comment by diezcami** [comment]
@envygeeks Ah, I see
Would it be possible to perhaps keep both ~~~ and ``` to cater to both old and new users?

**Comment by envygeeks** [comment]
That's not up to us, that's up to the creators of Kramdown and they chose not to support ```

**Comment by chriddyp** [comment]
what is the recommended work-around in the meantime? I've tried adding:

```
kramdown:
  input: GFM

markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
```

to my config, but my code blocks still aren't wrapped in `<pre>`s

**Comment by bux578** [comment]
Any updates on this? Especially with github now forcing us to use kramdown ...

**Comment by envygeeks** [comment]
@bux578 this was resolved in 3.1, we not default GFM on on <code>```</code> works.

**Comment by envygeeks** [comment]
I'm closing this issue as resolved as technically it is resolved if you use 3.1, once Github updates to 3.1 you'll be able to just keep working as is, if @parkr and @benbalter want, I'm happy to backport the changes for this into 3.0 so Github gets it now.

**Comment by parkr** [comment]
@envygeeks If you can backport off the `3.0-stable` branch, that would be much appreciated :)

**Comment by alexsb** [comment]
I still have this issue in 3.1.1. This is the generated code when I use a fenced code-block. 

```
<code class="highlighter-rouge">json
  {
    "name": "Test Heterogeneous 10x4",
    "path": "test_h10x4.csv",
    "size": [10, 4],
    "type": "table",
    "idtype": "patient",
    "columns": [
    {
      "name": "Gender",
      "value": {
        "type": "categorical",
        "categories": [
          {
            "name": "male",
            "color": "blue"
          },
          {
            "name": "female",
            "color": "red"
          }
        ]
      }
    },
    {
      "name": "Age",
      "value": {
        "type": "int",
        "range": [0, 100]
      }
    },
    {
      "name": "Value",
      "value": {
        "type": "real",
        "range": [0, 1]
      }
    }
  ]
}
</code>
```

On github pages, this renders in a `pre` tag, but it produces different HTML than {% highlight json %} .

**Comment by malyw** [comment]
Most of all this one wouldn't be reopened, I created another bug- https://github.com/jekyll/jekyll/issues/4515
Checked on a couple machines (Mac, Windows)- bug is still present in the latest Jekyll version.

**Comment by bux578** [comment]
Just a heads up: I got it working on a [gh-pages branch](https://github.com/acemod/ACE3/tree/gh-pages) using this configuration: [https://github.com/acemod/ACE3/blob/gh-pages/_config.yml](https://github.com/acemod/ACE3/blob/gh-pages/_config.yml).
[Fenced code blocks](https://github.com/acemod/ACE3/blob/gh-pages/wiki/development/setting-up-the-development-environment.md#71-disabling-cba-function-caching) are being [properly rendered to `<pre/>` code blocks](http://ace3mod.com/wiki/development/setting-up-the-development-environment.html#disabling-cba-function-caching). 
With Rouge I needed to modify all `´´´c++` to `´´´cpp`. _(i know this aren't backticks, just for highlighting purposes)_
