### ISSUE TITLE
Invalid converters are suggested as valid

### ISSUE THREAD

**Issue by TWiStErRob** [jekyll/jekyll#3772]
Forking off from #3770

[`allowed_custom_class`](https://github.com/jekyll/jekyll/blob/v2.5.3/lib/jekyll/converters/markdown.rb#L78) doesn't allow certain class names, but [`third_party_processors`](https://github.com/jekyll/jekyll/blob/v2.5.3/lib/jekyll/converters/markdown.rb#L39) return them and even print as suggested in "Valid options are ".

Minimalistic class in `_plugins`:
```ruby
class Jekyll::Converters::Markdown::My_Converter
end 
```

`_config.yml`:
```yaml
markdown: My_Converter
```

`jekyll build`:
```text
Invalid Markdown Processor: My_Converter
                    Valid options are [ maruku | rdiscount | kramdown | redcarpet | My_Converter ]
  Conversion error: Jekyll::Converters::Markdown encountered an error converting '_posts/....md/#excerpt'.
  Conversion error: Invalid Markdown Processor: My_Converter
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Markdown Processor: My_Converter
```

Is it really necessary to check against that regex? Let ruby decide what's a valid class and what's not ;)

**Comment by envygeeks** [comment]
Now that this is split out it's easier to see.  Now to address your concerns.  It is but it isn't necessary.  We want you to have custom markdown processors but we want them to come from a specific spot and we don't want you to load classes we have not approved so that you can do things we do not approve of.

This was mostly thought of as protection for Github, not for you.  Should they ever allow any amount of lenience on your builds we want to ensure you only do what we want you to do.  This is not to say they allow you to use a custom plugin, but if they add their own custom processor, we don't want you going insane and breaking the bounds and loading things that were not approved of.  The same way other safety checks are added in.  There are safety checks all over the place and more that can be added, I'm sure of it.

Onto the class name, an underscore is allowable by Ruby and we can surely add that to the list (no harm in that,) but I must also mention that that breaks common Ruby convention, it should really be called "MyConverter."

**Comment by TWiStErRob** [comment]
Yep, I agree and I thought there may be something like this behind. But don't miss the point, this doesn't change the fact that it's in the valid list and an error is thrown if you set it.

**Comment by parkr** [comment]
Is this fixed by #3771?

**Comment by envygeeks** [comment]
I believe it address this one and the other one.  That is part of the stuff I have coming out tomorrow.

**Comment by TWiStErRob** [comment]
Thanks for fixing!

I wanted to argue that adding `_` didn't fully fix the issue, but everywhere I looked it didn't show more than that. Now your regex matches all valid class name identifiers (according to at least 3 sources I checked). This means that it's not possbile to define a valid class and `allowed_custom_class` won't accept it. It looks like Ruby got it simple: for comparison Java allows accents and even Arabic and Chinese characters in identifiers.
