### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by d-jiao** [jekyll/jekyll#9774]
### Operating System

MacOS Sequoia 15.3.1

### Ruby Version

ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]

### Jekyll Version

I get the same error message as in "Current Behavior" when running bundle exec jekyll -v

### Expected Behavior

I expected my site to be built when running
`bundle exec jekyll serve`

### Current Behavior

This is the error message I got:
```
dj2526@Bob homepage % bundle exec jekyll serve  
/Users/dj2526/.gem/ruby/3.4.1/gems/jekyll-4.3.4/lib/jekyll.rb:26: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
/Users/dj2526/.gem/ruby/3.4.1/gems/jekyll-4.3.4/lib/jekyll.rb:28: warning: csv was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
bundler: failed to load command: jekyll (/Users/dj2526/.gem/ruby/3.4.1/bin/jekyll)
/Users/dj2526/.rubies/ruby-3.4.1/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require': cannot load such file -- csv (LoadError)
        from /Users/dj2526/.rubies/ruby-3.4.1/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/jekyll-4.3.4/lib/jekyll.rb:28:in '<top (required)>'
        from /Users/dj2526/.rubies/ruby-3.4.1/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/dj2526/.rubies/ruby-3.4.1/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/jekyll-4.3.4/exe/jekyll:8:in '<top (required)>'
        from /Users/dj2526/.gem/ruby/3.4.1/bin/jekyll:25:in 'Kernel#load'
        from /Users/dj2526/.gem/ruby/3.4.1/bin/jekyll:25:in '<top (required)>'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:58:in 'Kernel.load'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/cli.rb:455:in 'Bundler::CLI#exec'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor.rb:527:in 'Bundler::Thor.dispatch'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/exe/bundle:28:in 'block in <top (required)>'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
        from /Users/dj2526/.gem/ruby/3.4.1/gems/bundler-2.5.21/exe/bundle:20:in '<top (required)>'
        from /Users/dj2526/.gem/ruby/3.4.1/bin/bundle:25:in 'Kernel#load'
        from /Users/dj2526/.gem/ruby/3.4.1/bin/bundle:25:in '<main>'
```

### Relevant log output

```shell

```

**Comment by d-jiao** [comment]
I have tried all the fixes in https://github.com/jekyll/jekyll/issues/5423, but nothing worked out for me.

**Comment by markjconlon** [comment]
@d-jiao I was having a slighty different error than you just now however the root "bundler: failed to load command: jekyll" was there when using jekyll.

I pushed up my changes then
rm -rf directory
then git cloned my repo
bundle install
bundle exec jekyll serve

and all was good again. I don't really have an explanation but I tried a bunch of other "fixes" for about an hour before I tried that.

Hope this helps.

**Comment by d-jiao** [comment]
> [@d-jiao](https://github.com/d-jiao) I was having a slighty different error than you just now however the root "bundler: failed to load command: jekyll" was there when using jekyll.
> 
> I pushed up my changes then rm -rf directory then git cloned my repo bundle install bundle exec jekyll serve
> 
> and all was good again. I don't really have an explanation but I tried a bunch of other "fixes" for about an hour before I tried that.
> 
> Hope this helps.

Thanks for the reply! Unfortunately, I tried the same and it didn't resolve the issue...

**Comment by ashmaroli** [comment]
@d-jiao I suggest you update the Jekyll version in your Gemfile:
```diff
- gem "jekyll", "~> 4.3.1"
+ gem "jekyll", "~> 4.4"
```

**Comment by ic3man5** [comment]
I had the same issue, I had to add `gem "erb"` to the gemfile

**Comment by caizixian** [comment]
I have the same problem for `logger` Gem.

Additionally, liquid 4.0.4 tries to `bigdecimal` and results in the same `'Kernel.require': cannot load such file -- bigdecimal (LoadError)`

**Comment by monfresh** [comment]
That's because Ruby 3.4.x stopped including certain gems by default. For example, `bigdecimal` used to be a default gem in Ruby 3.3.x and older, but starting with Ruby 3.4.0, it is no longer included by default. You can see the list of default gems for each Ruby version on this website:

https://stdgems.org

So, you have 2 options:

- Use Ruby 3.3.8 with your Jekyll site
OR
- Add the missing gems to your Gemfile. For example:
```
gem "bigdecimal"
gem "logger"
gem "csv"
```
Then run `bundle install`

It would probably also make sense for the Jekyll maintainers to explicitly add those gems to the default Jekyll Gemfile, but in the meantime, the 2 solutions above will work.
